<!-- Portfolio Section -->
<h2>#BreakTheFakeCouncil Portal</h2>

<div class="jumbotron">
  <form method="post" action="<?php echo $this->url('articles', array('action' => 'search')); ?>">
    <div class="row">
      <div class="col">
        <input type="text" class="form-control" placeholder="%Keyword%" name="keyword">
      </div>
      <div class="col">
        <select type="text" class="form-control" name="category_id">
          <option value="">All Category</option>
          <?php if($this->categories): ?>
            <?php foreach ($this->categories as $row): ?>
          <option <?php if($this->searchFilter['category_id'] == $row->getId()): ?>selected<?php endif; ?> value="<?php echo $row->getId(); ?>"><?php echo $this->escapeHtml($row->getCategory()); ?></option>
            <?php endforeach; ?>
          <?php endif; ?>
        </select>
      </div>
      <div class="col">
        <button type="submit" class="btn btn-light mb-2">Search</button>
      </div>
    </div>
  </form>
</div>

<?php if($this->paginator): ?>
  <?php
      echo $this->paginationControl(
          $this->paginator,
          'sliding',
          "partial/home/paginator.phtml",
          array(
            'route' => 'articles',
            'search_by' => $this->search_by,
          )
      );
    ?>

<div class="row">
  <?php foreach ($this->paginator as $row): ?>
  <div class="col-lg-4 col-sm-6 portfolio-item">
    <div class="card h-100">
      <a href="<?php echo $this->escapeHtml($row->article_url);?>" target="_blank">
        <div>
          <img class="card-img-top" src="/img/site_article/<?php echo $this->escapeHtml($row->id);?>/cover.jpg" alt="">
          <img class="watermark" src="/img/site/<?php echo $this->escapeHtml($row->site_id);?>/photo-700x400.jpg" alt="">
        </div>

      </a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="<?php echo $this->escapeHtml($row->article_url);?>" target="_blank"><?php echo $this->escapeHtml($row->title);?></a>
        </h4>
        <small><strong><?php echo $this->escapeHtml($row->name);?></strong> <?php echo date('M d, Y', strtotime($row->created_datetime));?></small>
        <p class="card-text"><?php echo $this->getShortBody($row->body);?></p>
          <a href="<?php echo $this->escapeHtml($row->article_url);?>" target="_blank" class="btn btn-primary">Read More</a>
      </div>
    </div>
  </div>
  <?php endforeach; ?>
</div>

<?php
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        "partial/home/paginator.phtml",
        array(
          'route' => 'articles',
          'search_by' => $this->search_by,
        )
    );
  ?>
<?php endif; ?>

<!-- /.row -->
