<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Welcome
  <small><?php if ($user = $this->identity()): ?><?php echo $user->first_name; ?> <?php echo $user->last_name; ?><?php endif; ?></small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('member'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">My Site</li>
</ol>

<!-- Content Row -->
<div class="row">
  <!-- Sidebar Column -->
  <div class="col-lg-3 mb-4">
    <?php echo $this->partial('partial/member/menu.phtml', array(
        'route' => $this->route,
        'action' => $this->action,
    )); ?>
  </div>
  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <h2>Edit Site</h2>

    <hr>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>


     <div class="row">
       <div class="col-lg-12">
         <?php
        $form->setAttribute('action', $this->url('member-site', ['action' => 'edit', 'id' => $this->site->getId()]));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('site_url')) ?>
            <?= $this->formElement($form->get('site_url')) ?>
            <?= $this->formElementErrors()->render($form->get('site_url'), ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')) ?>
            <?= $this->formElement($form->get('name')) ?>
            <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')) ?>
            <?= $this->formElement($form->get('description')) ?>
            <?= $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('sitemap_url')) ?>
            <?= $this->formElement($form->get('sitemap_url')) ?>
            <?= $this->formElementErrors()->render($form->get('sitemap_url'), ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
          <?= $this->formLabel($form->get('category_id')) ?>
          <?= $this->formElement($form->get('category_id')) ?>
          <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
          <?php if(!is_null($this->photo)): ?>
          <div class="row">
            <div class="col-lg-4 col-sm-6 portfolio-item">
              Existing Photo:
              <img class="card-img-top" src="<?php echo $this->photo; ?>?rand=<?php echo time(); ?>" alt="Photo">
            </div>
          </div>
          <?php endif; ?>
          <?= $this->formLabel($form->get('photo')) ?>
          <?= $this->formFile($form->get('photo')) ?>
          <?= $this->formElementErrors()->render($form->get('photo'), ['class' => 'help-block']) ?>
          <ul class="help-block">
            <li>File Types: jpg</li>
            <li>Dimension at least: 700x400</li>
          </ul>
        </div>

        <div class="btn-group">
          <?php echo $this->formSubmit($form->get('submit')); ?>
          <a href="<?php echo $this->url('member-site'); ?>" class="btn btn-secondary">Cancel</a>
        </div>
        <?php echo $this->form()->closeTag();?>
       </div>
  </div>
  <!-- /.container-fluid -->
  </div>
</div>
<!-- /.row -->
